version: '3.8'

services:
  sensor_type:
    image: gosensor:latest
    environment:
      - GRPC_SERVER=gosensor-collector:50051
      - SENSOR_TYPE=temperature-{{.Task.Slot}}
      - API_SERVER=0.0.0.0:3000
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      - gosensor_network
    deploy:
      replicas: 50
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  gosensor_network:
    external:
      name: gosensor_network
